services:
  frontend:
    container_name: ${FRONTEND_HOST}
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
  db:
    container_name: ${DB_HOST}
    build:
      context: ./db
    expose:
      - ${DB_PORT}
    volumes:
      - db_data:/data/db
  backend:
    container_name: ${BACKEND_HOST}
    build:
      context: ./backend
    expose:
      - ${BACKEND_PORT}

volumes:
  db_data:
